### ISSUE TITLE
Solute.nameProperty is not migrated

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale-basics#52] opened 2023-01-18 17:06 UTC
Discovered while working on https://github.com/phetsims/ph-scale/issues/267, looks like we need this in the basics version too:

https://github.com/phetsims/phet-io-sim-specific/blob/fc3719921a606d45692ddada930da801ea6081c0/repos/ph-scale/js/ph-scale-migration-rules.ts#L33-L35

Not sure if there was a reason we kept it out, or if it was an oversight, AND if there are others that potentially need adding to.

**Comment by zepumph** [comment] 2023-01-18 17:07
Oh, but please this is on hold until we work out a long term solution for updating strings from pre-dynamic-locale days to master over in https://github.com/phetsims/joist/issues/899. Also tagging @samreid

**Comment by pixelzoom** [comment] 2023-01-18 17:46
As noted in https://github.com/phetsims/ph-scale/issues/267#issuecomment-1386210107:
> It requires revision to both ph-scale-migration-rules.ts and ph-scale-basics-migration-rules.ts.

But if you prefer to have a separate isue for each sim, that's fine.

**Comment by pixelzoom** [comment] 2023-01-23 18:28
Closing as duplicate of https://github.com/phetsims/ph-scale/issues/267.

**Closed by pixelzoom** 2023-01-23 18:28 UTC
Labels: dev:phet-io, status:on-hold, status:blocks-sim-publication
